name: Build the documentation
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
        contents: read
        pages: write
        id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: add doc-gen4
        run: lake -Kenv=dev update doc-gen4 -R

      - name: get mathlib cache
        continue-on-error: true
        run: |
          lake exe cache clean
          # We've been seeing many failures at this step recently because of network errors.
          # As a band-aid, we try twice.
          # The 'sleep 1' is small pause to let the network recover.
          lake exe cache get || (sleep 1; lake exe cache get)

      - name: build documentation
        run: lake build && lake build TacticsInLean:docs

      - name: Fix permissions
        run: |
          chmod -c -R +rX ".lake/build/doc" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .lake/build/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
